site_name: DomiNyan
repo_url: https://github.com/yifen9/DomiNyan
repo_name: DomiNyan
theme:
  name: material
nav:
  - Home: index.md
  - Viewer: viewer.md
extra_javascript:
  - js/viewer.index.js
  - js/viewer.loader.js
  - js/viewer.render.js
  - js/viewer.chart.js